Proyecto/Apps/App1/urls.py
from django.conf.urls import url,include
from django.urls import path
from .views import IndexView, DocentesView, GaleriaView, InformacionView, AcercaView, estdianteList
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
urlpatterns = [
    path('', IndexView.as_view()), 
    path('Inicio/', IndexView.as_view(),name='Inicio'),
    path('Docentes/', DocentesView.as_view(),name='Docentes'),
    path('Galeria/', GaleriaView.as_view(),name='Galeria'),
    path('Informacion/', estdianteList.as_view(),name='Informacion'),
    path('Acerca/',  estdianteList.as_view(),name='Acerca'),
    #path('registrar/', registrarusuario.as_view(),name='registrar'),
    path('login/', LoginView.as_view(template_name='Usuario/logiarse.html'),name = 'login'),

]

Proyecto/Proyecto/urls.py
from django.conf.urls import url,include
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib import admin
urlpatterns = [
    path('admin/', admin.site.urls),
    path('App1/', include(('Apps.App1.urls','app1'), namespace='app1')),  
    path('App2/', include(('Apps.App2.urls','app1'), namespace='app2')),  
    path('accounts/login/', LoginView.as_view(template_name='Usuario/logiarse.html'),name = 'login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    #path('reset/passwordReset', PasswordResetView, {'template_name : registration/password_reset_form.html','email_template_name:registration/password_reset_email.html'}, name = 'passwordReset'),
    #path('reset/passwordResetDone', PasswordResetDoneView, {'template_name : registration/password_reset_done.html'}, name='passwordResetDone'),
    #path('reset/<uidb64>/<token>',PasswordResetConfirmView, {'template_name : registration/password_reset_confirm.html'}, name='passwordResetConfirm'),
    #path('reset/done', PasswordResetCompleteView, {'template_name : registration/password_reset_complete.html'}, name='PasswordResetComplete'),
    
]

Proyecto/Apps/App1/models.py
from django.db import models

# Create your models here.

Proyecto/Apps/App1/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

#class RegistroForm(UserCreationForm):
#	class Meta:
#		model = User
#		fields = [
#			'username',
#		    'first_name',
#			'last_name',
#			'email',
#			]
#
#		labels= {
#		    'username':'Nombre de Usuario',
#		    'first_name':'Nombre',
#			'last_name':'Apellido',
#			'email': 'Correo',
#		}
#
#		widgets={
#			'username':forms.TextInput(attrs={'class':'form-control'}),
#			'first_name':forms.TextInput(attrs={'class':'form-control'}),
#			'last_name':forms.TextInput(attrs={'class':'form-control'}),
#			'email':forms.EmailInput(attrs={'class':'form-control'}),
#
#		}

Proyecto/Apps/App1/views.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import TemplateView, CreateView, ListView
from django.urls import reverse_lazy


# Create your views here.
class IndexView(TemplateView):  
	  template_name='index.html'

class DocentesView(TemplateView):  
	  template_name='docentes.html'  

class GaleriaView(TemplateView):  
	  template_name='galeria.html'

class InformacionView(TemplateView):  
	  template_name='informacion.html'

class AcercaView(TemplateView):  
	  template_name='acerca.html'

class estdianteList(TemplateView): 
	  template_name='acerca.html'

#class registrarusuario(CreateView):
#	  model = User
#	  template_name = "Usuario/registrar.html"
#	  form_class = RegistroForm
#	  success_url=reverse_lazy('app1:Inicio')	 

Proyecto/Apps/App1/templates/acerca.html
{% extends 'base.html' %}

{% block titulo %} Acerca {% endblock %}


{% block propio %}
Hola

{% endblock %}

Proyecto/Apps/App1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<title>{% block titulo %} Home {% endblock %} </title>
  <meta name="keywords" content="liceo Minerva, colegio liceo  Minervan, minerva, San pedro Sacatepequez San Marcos">
  <meta name="description" content="Pagina web del colegio liceo Minerva">

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}">
	<script src="{% static 'js/jquery.min.js' %}"></script>

	<script src="{% static 'bootstrap/js/bootstrap.js '%}"></script>

  <link rel="stylesheet" type="text/css" href="{% static 'css/estilos.css' %}">

</head>
<body>

{% block varnav %}
	<nav class="navbar navbar-inverse" style="background-color: rgba(02,49,59);width: 100%;margin:0px auto; position: fixed; margin-top: 5px;" >
{% endblock %}

    <div class="navbar-header">
      <span class="titulo2">Menu</span>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        
        <span class="sr-only"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav" >
        
        <li class="nav-item"><a class="nav-link" href="{% url 'app1:Inicio' %}">Inicio</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'app1:login' %}">Administracion</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'app1:Galeria' %}">Galeria</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'app1:Informacion' %}">Informacion</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'app1:Acerca' %}">Acerca de</a></li>

      </ul>
    </div>
  </div>
</nav>

  {% block footer %}

  <footer style="background-color: rgba(02,49,59, .9); width: 100%; position: absolute; bottom: 0">
  Todos los derechos reservados &copy; 2019
  <a style="float: right;" href="facebook.com">Siguenos en Facebook</a>Tel:<em>53292831</em>

</footer>
{% endblock %}

  {% block propio %}
  {% endblock %}


</body>
</html>

Proyecto/Apps/App1/templates/galeria.html
{% extends 'base.html' %}

{% block varnav %}
    <nav class="navbar navbar-inverse" style="background-color: rgba(02,49,59);width: 100%;margin:0px auto; position: flex; margin-top: 5px;" >
{% endblock %}

{% block propio %}
    <!-- Grid row -->

    <h1 class="text-center">Galeria de Imagenes</h1>
<div class="row">

  <!-- Grid column -->
  <div class="col-lg-4 col-md-12 mb-4">

    <!--Modal: Name-->
    <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg" role="document">

        <!--Content-->
        <div class="modal-content">

          <!--Body-->
          <div class="modal-body mb-0 p-0">

            <div class="embed-responsive embed-responsive-16by9 z-depth-1-half">
              <iframe class="embed-responsive-item" src="/static/Imagenes/1.jpg"
                allowfullscreen></iframe>
            </div>

          </div>

          <!--Footer-->
          <div class="modal-footer justify-content-center">
            <span class="mr-4">Nuestras Instalaciones!</span>
            <a type="button" class="btn-floating btn-sm btn-fb"><i class="fab fa-facebook-f"></i></a>
            <!--Twitter-->
            <a type="button" class="btn-floating btn-sm btn-tw"><i class="fab fa-twitter"></i></a>
            <!--Google +-->
            <a type="button" class="btn-floating btn-sm btn-gplus"><i class="fab fa-google-plus-g"></i></a>
            <!--Linkedin-->
            <a type="button" class="btn-floating btn-sm btn-ins"><i class="fab fa-linkedin-in"></i></a>

            <button type="button" class="btn btn-outline-primary btn-rounded btn-md ml-4" data-dismiss="modal">Close</button>

          </div>

        </div>
        <!--/.Content-->

      </div>
    </div>
    <!--Modal: Name-->

    <a><img class="img-fluid z-depth-1" src="/static/Imagenes/1.jpg" alt="video"
        data-toggle="modal" data-target="#modal1"></a>

  </div>
  <!-- Grid column -->

  <!-- Grid column -->
  <div class="col-lg-4 col-md-6 mb-4">

    <!--Modal: Name-->
    <div class="modal fade" id="modal6" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg" role="document">

        <!--Content-->
        <div class="modal-content">

          <!--Body-->
          <div class="modal-body mb-0 p-0">

            <div class="embed-responsive embed-responsive-16by9 z-depth-1-half">
              <iframe class="embed-responsive-item" src="/static/Imagenes/2.jpg"
                width="100%"></iframe>
            </div>

          </div>

          <!--Footer-->
          <div class="modal-footer justify-content-center">
            <span class="mr-4">Spread the word!</span>
            <a type="button" class="btn-floating btn-sm btn-fb"><i class="fab fa-facebook-f"></i></a>
            <!--Twitter-->
            <a type="button" class="btn-floating btn-sm btn-tw"><i class="fab fa-twitter"></i></a>
            <!--Google +-->
            <a type="button" class="btn-floating btn-sm btn-gplus"><i class="fab fa-google-plus-g"></i></a>
            <!--Linkedin-->
            <a type="button" class="btn-floating btn-sm btn-ins"><i class="fab fa-linkedin-in"></i></a>

            <button type="button" class="btn btn-outline-primary btn-rounded btn-md ml-4" data-dismiss="modal">Close</button>

          </div>

        </div>
        <!--/.Content-->

      </div>
    </div>
    <!--Modal: Name-->

    <a><img class="img-fluid z-depth-1" src="/static/Imagenes/2.jpg" alt="video"
        data-toggle="modal" data-target="#modal6"></a>

  </div>
  <!-- Grid column -->

  <!-- Grid column -->
  <div class="col-lg-4 col-md-6 mb-4">

    <!--Modal: Name-->
    <div class="modal fade" id="modal4" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg" role="document">

        <!--Content-->
        <div class="modal-content">

          <!--Body-->
          <div class="modal-body mb-0 p-0">

            <div class="embed-responsive embed-responsive-16by9 z-depth-1-half">
              <iframe class="embed-responsive-item" src="/static/Imagenes/3.jpg"
                width="100%"></iframe>
            </div>

          </div>

          <!--Footer-->
          <div class="modal-footer justify-content-center">
            <span class="mr-4">Spread the word!</span>
            <a type="button" class="btn-floating btn-sm btn-fb"><i class="fab fa-facebook-f"></i></a>
            <!--Twitter-->
            <a type="button" class="btn-floating btn-sm btn-tw"><i class="fab fa-twitter"></i></a>
            <!--Google +-->
            <a type="button" class="btn-floating btn-sm btn-gplus"><i class="fab fa-google-plus-g"></i></a>
            <!--Linkedin-->
            <a type="button" class="btn-floating btn-sm btn-ins"><i class="fab fa-linkedin-in"></i></a>

            <button type="button" class="btn btn-outline-primary btn-rounded btn-md ml-4" data-dismiss="modal">Close</button>

          </div>

        </div>
        <!--/.Content-->

      </div>
    </div>
    <!--Modal: Name-->

    <a><img class="img-fluid z-depth-1" src="/static/Imagenes/3.jpg" alt="video"
        data-toggle="modal" data-target="#modal4"></a>

  </div>
  <!-- Grid column -->

</div>
<!-- Grid row -->

<!-- Grid row -->
<div class="row">

  <!-- Grid column -->
  <div class="col-lg-4 col-md-12 mb-4">

    <!--Modal: Name-->
    <div class="modal fade" id="modal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg" role="document">

        <!--Content-->
        <div class="modal-content">

          <!--Body-->
          <div class="modal-body mb-0 p-0">

            <div class="embed-responsive embed-responsive-16by9 z-depth-1-half">
              <iframe class="embed-responsive-item" src="/static/Imagenes/4.jpg"
                allowfullscreen></iframe>
            </div>

          </div>

          <!--Footer-->
          <div class="modal-footer justify-content-center">
            <span class="mr-4">Spread the word!</span>
            <a type="button" class="btn-floating btn-sm btn-fb"><i class="fab fa-facebook-f"></i></a>
            <!--Twitter-->
            <a type="button" class="btn-floating btn-sm btn-tw"><i class="fab fa-twitter"></i></a>
            <!--Google +-->
            <a type="button" class="btn-floating btn-sm btn-gplus"><i class="fab fa-google-plus-g"></i></a>
            <!--Linkedin-->
            <a type="button" class="btn-floating btn-sm btn-ins"><i class="fab fa-linkedin-in"></i></a>

            <button type="button" class="btn btn-outline-primary btn-rounded btn-md ml-4" data-dismiss="modal">Close</button>

          </div>

        </div>
        <!--/.Content-->

      </div>
    </div>
    <!--Modal: Name-->

    <a><img class="img-fluid z-depth-1" src="/static/Imagenes/4.jpg" alt="video"
        data-toggle="modal" data-target="#modal2"></a>

  </div>
  <!-- Grid column -->

  <!-- Grid column -->
  <div class="col-lg-4 col-md-6 mb-4">

    <!--Modal: Name-->
    <div class="modal fade" id="modal5" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg" role="document">

        <!--Content-->
        <div class="modal-content">

          <!--Body-->
          <div class="modal-body mb-0 p-0">

            <div class="embed-responsive embed-responsive-16by9 z-depth-1-half">
              <iframe class="embed-responsive-item" src="/static/Imagenes/5.jpg"
                allowfullscreen></iframe>
            </div>

          </div>

          <!--Footer-->
          <div class="modal-footer justify-content-center">
            <span class="mr-4">Spread the word!</span>
            <a type="button" class="btn-floating btn-sm btn-fb"><i class="fab fa-facebook-f"></i></a>
            <!--Twitter-->
            <a type="button" class="btn-floating btn-sm btn-tw"><i class="fab fa-twitter"></i></a>
            <!--Google +-->
            <a type="button" class="btn-floating btn-sm btn-gplus"><i class="fab fa-google-plus-g"></i></a>
            <!--Linkedin-->
            <a type="button" class="btn-floating btn-sm btn-ins"><i class="fab fa-linkedin-in"></i></a>

            <button type="button" class="btn btn-outline-primary btn-rounded btn-md ml-4" data-dismiss="modal">Close</button>

          </div>

        </div>
        <!--/.Content-->

      </div>
    </div>
    <!--Modal: Name-->

    <a><img class="img-fluid z-depth-1" src="/static/Imagenes/5.jpg" alt="video"
        data-toggle="modal" data-target="#modal5"></a>

  </div>
  <!-- Grid column -->

  <!-- Grid column -->
  <div class="col-lg-4 col-md-6 mb-4">

    <!--Modal: Name-->
    <div class="modal fade" id="modal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg" role="document">

        <!--Content-->
        <div class="modal-content">

          <!--Body-->
          <div class="modal-body mb-0 p-0">

            <div class="embed-responsive embed-responsive-16by9 z-depth-1-half">
              <iframe class="embed-responsive-item" src="/static/Imagenes/6.jpg"
                allowfullscreen></iframe>
            </div>

          </div>

          <!--Footer-->
          <div class="modal-footer d-block d-md-flex justify-content-center">
            <span class="mr-4">Spread the word!</span>
            <a type="button" class="btn-floating btn-sm btn-fb"><i class="fab fa-facebook-f"></i></a>
            <!--Twitter-->
            <a type="button" class="btn-floating btn-sm btn-tw"><i class="fab fa-twitter"></i></a>
            <!--Google +-->
            <a type="button" class="btn-floating btn-sm btn-gplus"><i class="fab fa-google-plus-g"></i></a>
            <!--Linkedin-->
            <a type="button" class="btn-floating btn-sm btn-ins"><i class="fab fa-linkedin-in"></i></a>

            <button type="button" class="btn btn-outline-primary btn-rounded btn-md ml-4" data-dismiss="modal">Close</button>

          </div>

        </div>
        <!--/.Content-->

      </div>
    </div>
    <!--Modal: Name-->

    <a><img class="img-fluid z-depth-1" src="/static/Imagenes/6.jpg" alt="video"
        data-toggle="modal" data-target="#modal3"></a>

  </div>
  <!-- Grid column -->

</div>

<style type="text/css">
    img
    {
        width: 100%;
        margin: 2px 0px;
    } 

</style>
<!-- Grid row -->
  {% endblock %}

  {% block footer %}

  {% endblock %}

Proyecto/Apps/App1/templates/index.html
{% extends 'base.html' %}

{% block titulo %} Inicio {% endblock %}

{% block varnav%}
<nav class="navbar navbar-inverse" style="background-color: rgb(02,49,59);width: 100%; position: flex; margin-top:5px">
{% endblock %}

{% block propio %}


<div class="container">
  <div class="col-md-01">
    <div id="caroucel1" class="carousel slide " data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carousel1" data-slide-to="1" ></li>
        <li data-target="#carousel1" data-slide-to="2" ></li>
      </ol>

      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img  src="/static/Imagenes/1.jpg" class="img-responsive" alt="">
          <div class="carousel-caption">
            <p>Modernas Instalaciones</p> 
          </div>
        </div>

        <div class="item">
          <img  src="/static/Imagenes/3.jpg" class="img-responsive" alt="">
          <div class="carousel-caption">
            <p>Amplias instalaciones</p> 
          </div>
        </div>

        <div class="item">
          <img  src="/static/Imagenes/1.jpg" class="img-responsive" alt="">
          <div class="carousel-caption">
            <p>Instituto Nacional de educacion Diversificada</p> 
          </div>
        </div>
        </div>

        <a href="#caroucel1" class="left carousel-control" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden=true></span>
            <span class="sr-only">Anterior</span>
          </a>
          <a href="#caroucel1" class="right carousel-control" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden=true></span>
            <span class="sr-only">Siguiente</span>
          </a>
    </div>
  </div>
</div>


{% endblock %}

Proyecto/Apps/App1/templates/informacion.html
{% extends 'base.html' %}

{% block titulo %} Informacion {% endblock %}

{% block propio %}
hola
{% endblock %}