Proyecto/Apps/App2/urls.py
from django.conf.urls import url,include
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import IndexView,registrarusuario, RegistrarDocentesView, RegistrarEstudiantesView, AdministrarView, RegistrarCarrerasView, RegistrarCursosView,registrarView, registradoView, NotasView, listarCarrerasView, listarCursosView, listarDocentesView, listarEstudiantesView,listarNotasView, DocenteUpdate, EstudiantesUpdate, CursoUpdate, CarreaUpdate,NotasUpdate, DocenteDelete, EstudianteDelete, CursoDelete, CarreraDelete
urlpatterns = [
    path('registrar/', login_required(registrarusuario.as_view()),name='registrar'),
    path('Inicio/', login_required(IndexView.as_view()),name='Inicio'),
    path('RegistrarDocentes/',login_required (RegistrarDocentesView.as_view()), name='RegistrarDocentes'),
    path('RegistrarEstudiantes/',login_required (RegistrarEstudiantesView.as_view()),name='RegistrarEstudiantes'),
    path('RegistrarCarrera/',login_required(RegistrarCarrerasView.as_view()),name='RegistrarCarrera'),
    path('RegistrarCurso/',login_required(RegistrarCursosView.as_view()),name='RegistrarCurso'),
    path('SubirNotas/',login_required(NotasView.as_view()),name='SubirNotas'),
    path('Administrar/',login_required (AdministrarView.as_view()),name='Administrar'),
    path('Registros/', login_required(registrarView.as_view()),name='Registros'),
    path('Registrado/', login_required(registradoView.as_view()),name='Registrado'),
    path('listarCarreras/',login_required (listarCarrerasView.as_view()),name='listarCarreras'),
    path('listarCursos/',login_required (listarCursosView.as_view()),name='listarCursos'),
    path('listarDocentes/',login_required (listarDocentesView.as_view()),name='listarDocentes'),
    path('listarEstudiantes/', login_required(listarEstudiantesView.as_view()),name='listarEstudiantes'),
    path('listarNotas/', login_required(listarNotasView.as_view()),name='listarNotas'),
    path('ActualizarDocente/<pk>',login_required(DocenteUpdate.as_view()),name='ActualizarDocente'),
    path('ActualizarEstudiante/<pk>',login_required(EstudiantesUpdate.as_view()),name='ActualizarEstudiante'),
    path('ActualizarCurso/<pk>',login_required(CursoUpdate.as_view()),name='ActualizarCurso'),
    path('ActualizarDocente/<pk>',login_required(DocenteUpdate.as_view()),name='ActualizarDocente'),
    path('ActualizarNotas/<pk>',login_required(NotasUpdate.as_view()),name='ActualizarNotas'),
    path('DocenteDelete/<pk>',login_required(DocenteDelete.as_view()),name='DocenteDelete'),
    path('EstudianteDelete/<pk>',login_required(EstudianteDelete.as_view()),name='EstudianteDelete'),
    path('CursoDelete/<pk>',login_required(CursoDelete.as_view()),name='CursoDelete'),
    path('CarreraDelete/<pk>',login_required(CarreraDelete.as_view()),name='CarreraDelete'),
]

Proyecto/Proyecto/urls.py
from django.conf.urls import url,include
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib import admin
urlpatterns = [
    path('admin/', admin.site.urls),
    path('App1/', include(('Apps.App1.urls','app1'), namespace='app1')),  
    path('App2/', include(('Apps.App2.urls','app1'), namespace='app2')),  
    path('accounts/login/', LoginView.as_view(template_name='Usuario/logiarse.html'),name = 'login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    #path('reset/passwordReset', PasswordResetView, {'template_name : registration/password_reset_form.html','email_template_name:registration/password_reset_email.html'}, name = 'passwordReset'),
    #path('reset/passwordResetDone', PasswordResetDoneView, {'template_name : registration/password_reset_done.html'}, name='passwordResetDone'),
    #path('reset/<uidb64>/<token>',PasswordResetConfirmView, {'template_name : registration/password_reset_confirm.html'}, name='passwordResetConfirm'),
    #path('reset/done', PasswordResetCompleteView, {'template_name : registration/password_reset_complete.html'}, name='PasswordResetComplete'),
    
]

Proyecto/Apps/App2/models.py
from django.db import models

# Create your models here.

class Carrera(models.Model):
	idcarrera = models.IntegerField(primary_key=True)
	nombre = models.CharField(max_length=25)

	def __str__ (self):
		return '{}'.format(self.nombre)

class grado(models.Model):
	idgrado = models.IntegerField(primary_key=True)
	grado = models.IntegerField()
	seccion = models.CharField(max_length=25)

	def __str__ (self):
		return '{} {}'.format(self.grado, self.seccion)


class Docente(models.Model):
	iddocente = models.IntegerField(primary_key=True)
	pnombre = models.CharField(max_length=25)
	snombre = models.CharField(max_length=25)
	pApellido = models.CharField(max_length=25)
	sApellido = models.CharField(max_length=25)
	fNacimiento = models.CharField(max_length=25)
	direccion= models.CharField(max_length=25)
	correo=models.EmailField(max_length=25)


	def __str__ (self):
		return '{} {}'.format(self.pnombre, self.pApellido)


class Estudiante(models.Model):
	idestudiante = models.IntegerField(primary_key=True)
	pnombre = models.CharField(max_length=25)
	snombre = models.CharField(max_length=25)
	pApellido = models.CharField(max_length=25)
	sApellido = models.CharField(max_length=25)
	fNacimiento= models.CharField(max_length=25)
	direccion= models.CharField(max_length=25)
	correo=models.EmailField(max_length=25)
	idcarrera= models.ForeignKey(Carrera, on_delete=models.CASCADE)
	iddocente=models.ManyToManyField(Docente)
	idgrado= models.ForeignKey(grado, on_delete=models.CASCADE)

	def __str__ (self):
		return '{} {}'.format(self.pnombre,self.pApellido)


class Curso(models.Model):
	idcurso = models.IntegerField(primary_key=True)
	idcarrera = models.ForeignKey(Carrera, on_delete=models.CASCADE)
	iddocente = models.ForeignKey(Docente, on_delete=models.CASCADE)
	nombre = models.CharField(max_length=25)
	idgrado = models.ForeignKey(grado, on_delete=models.CASCADE)

	def __str__ (self):
		return '{}'.format(self.nombre)

class Notas(models.Model):
	nota = models.IntegerField();
	idcurso = models.ForeignKey(Curso, on_delete=models.CASCADE)
	idcarrera = models.ForeignKey(Carrera, on_delete=models.CASCADE)
	iddocente = models.ForeignKey(Docente, on_delete=models.CASCADE)
	idestudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE)
	idgrado= models.ForeignKey(grado, on_delete=models.CASCADE)

	def __str__ (self):
		return '{}'.format(self.nota)

Proyecto/Apps/App2/forms.py
from django.forms import ModelForm
from django import forms
from .models import Docente, Estudiante, Curso, Carrera, Notas, grado
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class EstudianteForm(ModelForm):
	class Meta:
		model = Estudiante
		fields = '__all__'

		labels={
			'idestudiante':'Codigo Estudiante',
			'pnombre':'Primer Nombre',
			'snombre':'Segundo Nombre',
			'pApellido':'Primer Apellido',
			'sApellido':'SegundoApellido',
			'idgrado':'Grado',
			'fNacimiento':'Fecha de Nacimiento',
			'direccion': 'Direccion',
			'correo':'Correo Electronico',
			'idcarrera':'Nombre de la Carrera',
			'iddocente':'Seleccione los Docentes del Alumno',

		}

		widgets = {
			'idestudiante':forms.NumberInput(attrs={'class':'form-control'}),
			'pnombre':forms.TextInput(attrs={'class':'form-control'}),
			'snombre': forms.TextInput(attrs={'class':'form-control'}),
			'pApellido': forms.TextInput(attrs={'class':'form-control'}),
			'sApellido': forms.TextInput(attrs={'class':'form-control'}),
			'idgrado': forms.Select(attrs={'class':'form-control'}),
			'fNacimiento': forms.SelectDateWidget(years=range(1950,2030), attrs={'class':'fecha'}),
			'direccion': forms.TextInput(attrs={'class':'form-control'}),
			'correo': forms.EmailInput(attrs={'class':'form-control'}),
			'idcarrera': forms.Select(attrs={'class':'form-control'}),
			'iddocente': forms.CheckboxSelectMultiple(),

		}

class DocenteForm(ModelForm):
	class Meta:
		model = Docente
		fields = '__all__'

		labels={
		
			'iddocente':'Codigo del Docente',
			'pnombre':'Primer Nombre',
			'snombre':'Segundo Nombre',
			'pApellido':'Primer Apellido',
			'sApellido':'SegundoApellido',
			'fNacimiento':'Fecha de Nacimiento',
			'direccion': 'Direccion',
			'correo':'Correo Electronico',
		}

		widgets = {
			'iddocente':forms.NumberInput(attrs={'class':'form-control'}),
			'pnombre':forms.TextInput(attrs={'class':'form-control'}),
			'snombre': forms.TextInput(attrs={'class':'form-control'}),
			'pApellido': forms.TextInput(attrs={'class':'form-control'}),
			'sApellido': forms.TextInput(attrs={'class':'form-control'}),
			'fNacimiento': forms.SelectDateWidget(years=range(1950,2030), attrs={'class':'fecha'}),
			'direccion': forms.TextInput(attrs={'class':'form-control'}),
			'correo': forms.EmailInput(attrs={'class':'form-control'}),

		}



class CarreraForm(ModelForm):
	class Meta:
		model = Carrera
		fields = '__all__'

		labels={
		    'idcarrera': 'Codigo de la Carrera',
		    'nombre': 'Nombre de la carrera',
		}

		widgets = {
			'idcarrera':forms.NumberInput(attrs={'class':'form-control'}),
			'nombre':forms.TextInput(attrs={'class':'form-control'}),
		}

class GradoForm(ModelForm):
	class Meta:
		model = grado
		fields = '__all__'

		labels={
		    'idgrado': 'Codigo de grado',
		    'grado': 'grado',
		    'seccion': 'Seccion',
		}

		widgets = {
			'idgrado':forms.NumberInput(attrs={'class':'form-control'}),
			'grado':forms.NumberInput(attrs={'class':'form-control'}),
			'seccion':forms.TextInput(attrs={'class':'form-control'}),
		}

class CursoForm(ModelForm):
	class Meta:
		model = Curso
		fields = '__all__'

		labels={
		    'idcurso': 'Codigo del curso',
		    'idcarrera': 'Nombre de la carrera',
		    'iddocente': 'Nombre del docente',
		    'nombre':'nombre del curso',
		    'idgrado': 'Grado',
		}

		widgets = {
			'idcurso':forms.NumberInput(attrs={'class':'form-control'}),
			'idcarrera':forms.Select(attrs={'class':'form-control'}),
			'iddocente':forms.Select(attrs={'class':'form-control'}),
			'nombre':forms.TextInput(attrs={'class':'form-control'}),
			'idgrado':forms.Select(attrs={'class':'form-control'}),
		}

class NotasForm(ModelForm):
	class Meta:
		model = Notas
		fields = '__all__'

		labels={
		    'nota': 'Ingrese la nota',
		    'idcurso': 'Seleccione el Curso',
		    'idcarrera': 'Seleccione la Carrera',
		    'iddocente': 'Codigo del Docente',
		    'idestudiante': 'Nombre del Estudiante',
		    'idgrado': 'Grado',
		}

		widgets = {
			'nota':forms.NumberInput(attrs={'class':'form-control'}),
			'idcurso':forms.Select(attrs={'class':'form-control'}),
			'idcarrera':forms.Select(attrs={'class':'form-control'}),
			'iddocente':forms.Select(attrs={'class':'form-control'}),
			'idestudiante':forms.Select(attrs={'class':'form-control'}),
			'idgrado':forms.Select(attrs={'class':'form-control'}),
		}

class RegistroForm(UserCreationForm):
	class Meta:
		model = User
		fields = [
			'username',
		    'first_name',
			'last_name',
			'email',
			]

		labels= {
		    'username':'Nombre de Usuario',
		    'first_name':'Nombre',
			'last_name':'Apellido',
			'email': 'Correo',
		}

		widgets={
			'username':forms.TextInput(attrs={'class':'form-control'}),
			'first_name':forms.TextInput(attrs={'class':'form-control'}),
			'last_name':forms.TextInput(attrs={'class':'form-control'}),
			'email':forms.EmailInput(attrs={'class':'form-control'}),

		}

Proyecto/Apps/App2/views.py
from django.views.generic import TemplateView, CreateView, ListView, UpdateView, DeleteView
from .forms import  DocenteForm, NotasForm, EstudianteForm, CursoForm, CarreraForm, NotasForm, RegistroForm
from .models import Docente, Notas, Estudiante, Curso, Carrera, Notas
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy


# Create your views here.
class IndexView(TemplateView):  
	  template_name='Registrar/index2.html'

class registrarusuario(CreateView):
	  model = User
	  template_name = "Registrar/registrar.html"
	  form_class = RegistroForm
	  success_url=reverse_lazy('app2:Inicio')

class RegistrarDocentesView(CreateView):  
	  template_name='Registrar/Registrar_Docente.html'
	  model =Docente
	  form_class= DocenteForm
	  success_url=reverse_lazy('app2:Registrado')

class RegistrarEstudiantesView(CreateView):  
	  template_name='Registrar/Registrar_Estudiante.html'
	  model = Estudiante
	  form_class= EstudianteForm
	  success_url=reverse_lazy('app2:Registrado')	

class RegistrarCarrerasView(CreateView):  
	  template_name='Registrar/Registrar_Carrera.html'
	  model = Carrera
	  form_class= CarreraForm
	  success_url=reverse_lazy('app2:Registrado')

class RegistrarCursosView(CreateView):  
	  template_name='Registrar/Registrar_Curso.html'
	  model = Curso
	  form_class= CursoForm
	  success_url=reverse_lazy('app2:Registrado')

class NotasView(CreateView):  
	  template_name='Registrar/SubirNotas.html'
	  model = Notas
	  form_class = NotasForm
	  success_url=reverse_lazy('app2:Registrado')


class AdministrarView(TemplateView):  
	  template_name='Registrar/Administrar.html'

class registrarView(TemplateView):  
	  template_name='Registrar/Registros.html'


class registradoView(TemplateView):  
	  template_name='Registrar/Registrado.html'


class listarCarrerasView(ListView):
	  model = Carrera
	  template_name = 'listarRegistros/verCarrera.html'


class listarCursosView(ListView):
	  model = Curso
	  template_name = 'listarRegistros/VerCursos.html'


class listarDocentesView(ListView):
	  model = Docente
	  template_name = 'listarRegistros/verDocentes.html'

class listarEstudiantesView(ListView):
	  model = Estudiante
	  template_name = 'listarRegistros/VerEstudiantes.html'

class listarNotasView(ListView):
	  model = Notas
	  template_name = 'listarRegistros/VerNotas.html'

class DocenteUpdate(UpdateView):  
	  template_name='Actualizar/docentes.html'
	  model =Docente
	  form_class= DocenteForm
	  success_url=reverse_lazy('app2:listarDocentes')

class EstudiantesUpdate(UpdateView):  
	  template_name='Actualizar/estudiantes.html'
	  model =Estudiante
	  form_class= EstudianteForm
	  success_url=reverse_lazy('app2:listarEstudiantes')

class CursoUpdate(UpdateView):  
	  template_name='Actualizar/curso.html'
	  model =Curso
	  form_class= CursoForm
	  success_url=reverse_lazy('app2:listarCursos')

class CarreaUpdate(UpdateView):  
	  template_name='Actualizar/Carrera.html'
	  model = Carrera
	  form_class= CarreraForm
	  success_url=reverse_lazy('app2:listarCarreras')

class NotasUpdate(UpdateView):  
	  template_name='Actualizar/Notas.html'
	  model = Notas
	  form_class= NotasForm
	  success_url=reverse_lazy('app2:listarNotas')

class DocenteDelete(DeleteView):
	  model = Docente
	  template_name = 'Eliminar/docente.html'
	  success_url=reverse_lazy('app2:listarDocentes') 

class EstudianteDelete(DeleteView):
	  model = Estudiante
	  template_name = 'Eliminar/estudiante.html'
	  success_url=reverse_lazy('app2:listarEstudiantes') 

class CursoDelete(DeleteView):
	  model = Curso
	  template_name = 'Eliminar/curso.html'
	  success_url=reverse_lazy('app2:listarCursos') 

class CarreraDelete(DeleteView):
	  model = Carrera
	  template_name = 'Eliminar/carrera.html'
	  success_url=reverse_lazy('app2:listarCarreras') 

Proyecto/Apps/App2/templates/ListarRegistros/VerCursos.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
		<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}">
</head>
<body>
<center>
	<form class="navbar-search" method="post" action="#" style="margin: 15px">
		{% csrf_token %}
		<input type="text" class="search-query" placeholder="Buscar" name="buscar">
		<input type="submit" class="btn btn-primary"  value="Buscar">
	</form>
</center>

<table class="table table-hover table-responsive table-bordered" style="margin: 0px auto; width: 90%">
	<thead>
		<tr>
			<th scope="col">Codigo</th>
			<th scope="col">Carrera</th>
			<th scope="col">Docente</th>
			<th scope="col">Nombre</th>
			<th scope="col">Grado</th>
			<th scope="col">Acciones</th>
		</tr>
	</thead>
	<tbody>
		{% if object_list %}

		{% for Curso in object_list %}

		<tr>
			<th scope="row">{{Curso.idcurso}}</th>
			<td>{{Curso.idcarrera}}</td>
			<td>{{Curso.iddocente}}</td>
			<td>{{Curso.nombre}}</td>
			<td>{{Curso.grado}}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'app2:ActualizarCurso' Curso.idcurso %}"">Editar</a>
				<a class="btn btn-danger" href="{% url 'app2:CursoDelete' Curso.idcurso %}">Eliminar</a>	
			</td>
		</tr>

		{% endfor %}
		{% else %}
		<h1>No hay registros</h1>
		{% endif%}
	</tbody>
</table>

<center>
	<a class="btn btn-danger" href="{% url 'app2:Administrar' %}" style="margin: 15px">Volver</a>
</center>

</body>
</html>

Proyecto/Apps/App2/templates/ListarRegistros/VerEstudiantes.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
		<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}">
</head>
<body>
<center>
	<form class="navbar-search" method="post" action="#" style="margin: 10px">
		{% csrf_token %}
		<input type="text" class="search-query" placeholder="Buscar" name="buscar">
		<input type="submit" class="btn btn-primary"  value="Buscar">
	</form>
</center>

<table class="table table-hover table-responsive table-bordered" style="margin:10px auto; width: 99%">
	<thead>
		<tr>
			<th scope="col">#</th>
			<th scope="col">Nombre</th>
			<th scope="col">Fecha de Nacimiento</th>
			<th scope="col">Direccion</th>
			<th scope="col">Correo</th>
			<th scope="col">Seccion</th>
			<th scope="col">Carrera</th>
			<th scope="col">Docentes</th>
			<th scope="col">Acciones</th>

		</tr>
	</thead>
	<tbody>
		{% if object_list %}

		{% for Estudiante in object_list %}

		<tr>
			<th scope="row">{{Estudiante.idestudiante}}</th>
			<td>{{Estudiante.pnombre}} {{Estudiante.snombre}} {{Estudiante.pApellido}} {{Estudiante.sApellido}}</td>
			<td>{{Estudiante.fNacimiento}}</td>
			<td>{{Estudiante.direccion}}</td>
			<td>{{Estudiante.correo}}</td>
			<td>{{Estudiante.seccion}}</td>
			<td>{{Estudiante.idcarrera}}</td>
			{% for e in Estudiante.iddocente.all %}
			<td> {{e.pnombre}} {{e.pApellido}}</td>
			{% endfor %}
			<td>
				<a class="btn btn-primary" href="{% url 'app2:ActualizarEstudiante' Estudiante.idestudiante %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'app2:EstudianteDelete' Estudiante.idestudiante %}">Eliminar</a>	
			</td>
		</tr>

		{% endfor %}
		{% else %}
		<h1>No hay registros</h1>
		{% endif%}
	</tbody>
</table>

<center>
	<a class="btn btn-danger" href="{% url 'app2:Administrar' %}" style="margin: 15px">Volver</a>
</center>

</body>
</html>

Proyecto/Apps/App2/templates/ListarRegistros/VerNotas.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
		<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}">
</head>
<body>
<center>
	<form class="navbar-search" method="post" action="#" style="margin: 10px">
		{% csrf_token %}
		<input type="text" class="search-query" placeholder="Buscar" name="buscar">
		<input type="submit" class="btn btn-primary"  value="Buscar">
	</form>
</center>
<table class="table table-hover table-responsive table-bordered" style="margin: 0px auto; width: 99%">
	<thead>
		<tr>
			<th scope="col">Nota</th>
			<th scope="col">Curso</th>
			<th scope="col">Carrera</th>
			<th scope="col">Docente</th>
			<th scope="col">Estudiante</th>
			<th scope="col">Grado</th>
			<th scope="col">Acciones</th>
		</tr>
	</thead>
	<tbody>
		{% if object_list %}

		{% for Notas in object_list %}

		<tr>
			<th scope="row">{{Notas.nota}}</th>
			<td>{{Notas.idcurso}}</td>
			<td>{{Notas.idcarrera}}</td>
			<td>{{Notas.iddocente}}</td>
			<td>{{Notas.idestudiante}}</td>
			<td>{{Notas.idgrado}}</td>

			<td>
				<a class="btn btn-primary" href="{% url 'app2:ActualizarNotas' Notas.id %}">Actualizar</a>
			</td>
		</tr>

		{% endfor %}
		{% else %}
		<h1>No hay registros</h1>
		{% endif%}
	</tbody>
</table>

<center>
	<a class="btn btn-danger" href="{% url 'app2:Administrar' %}" style="margin: 15px">Volver</a>
</center>

</body>
</html>

Proyecto/Apps/App2/templates/ListarRegistros/verCarrera.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
		<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}">
</head>
<body>
<center>
	<form class="navbar-search" method="post" action="#" style="margin: 15px">
		{% csrf_token %}
		<input type="text" class="search-query" placeholder="Buscar" name="buscar">
		<input type="submit" class="btn btn-primary"  value="Buscar">
	</form>
</center>

<table class="table table-hover table-responsive table-bordered" style="margin: 0px auto; width: 90%">
	<thead>
		<tr>
			<th scope="col">ID</th>
			<th scope="col">Nombre</th>
			<th scope="col">Acciones</th>
		</tr>
	</thead>
	<tbody>
		{% if object_list %}

		{% for Carrera in object_list %}

		<tr>
			<th scope="row">{{Carrera.idcarrera}}</th>
			<td>{{Carrera.nombre}}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'app2:ActualizarEstudiante' Carrera.idcarrera %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'app2:CarreraDelete' Carrera.idcarrera %}">Eliminar</a>	
			</td>
		</tr>

		{% endfor %}
		{% else %}
		<h1>No hay registros</h1>
		{% endif%}
	</tbody>
</table>

<center>
	<a class="btn btn-danger" href="{% url 'app2:Administrar' %}" style="margin: 15px">Volver</a>
</center>

</body>
</html>

Proyecto/Apps/App2/templates/ListarRegistros/verDocentes.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
		<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}">
</head>
<body>
<center>
	<form class="navbar-search" method="post" action="#" style="margin: 10px">
		{% csrf_token %}
		<input type="text" class="search-query" placeholder="Buscar" name="buscar">
		<input type="submit" class="btn btn-primary"  value="Buscar">
	</form>
</center>
<table class="table table-hover table-responsive table-bordered" style="margin: 0px auto; width: 99%">
	<thead>
		<tr>
			<th scope="col">#</th>
			<th scope="col">Nombre</th>
			<th scope="col">Fecha de Nacimiento</th>
			<th scope="col">Direccion</th>
			<th scope="col">Correo</th>
			<th scope="col">Acciones</th>
		</tr>
	</thead>
	<tbody>
		{% if object_list %}

		{% for Docente in object_list %}

		<tr>
			<th scope="row">{{Docente.iddocente}}</th>
			<td>{{Docente.pnombre}} {{Docente.snombre}} {{Docente.pApellido}} {{Docente.sApellido}}</td>
			<td>{{Docente.fNacimiento}}</td>
			<td>{{Docente.direccion}}</td>
			<td>{{Docente.correo}}</td>

			<td>
				<a class="btn btn-primary" href="{% url 'app2:ActualizarDocente' Docente.iddocente %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'app2:DocenteDelete' Docente.iddocente %}">Eliminar</a>	
			</td>
		</tr>

		{% endfor %}
		{% else %}
		<h1>No hay registros</h1>
		{% endif%}
	</tbody>
</table>

<center>
	<a class="btn btn-danger" href="{% url 'app2:Administrar' %}" style="margin: 15px">Volver</a>
</center>

</body>
</html>